version: '3.8'

networks:
        mysql:
        web:

volumes:
        monica:
                name: monica
        mysql:
                name: mysql

services:
        mysql:
                container_name: mysql
                image: mysql:5.7
                restart: unless-stopped
                networks:
                        - mysql
                environment:
                        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
                volumes:
                        - mysql:/var/lib/mysql
                labels:
                        - traefik.enable=false
        monica:
                container_name: monica
                build: ./monica-app
                restart: unless-stopped
                depends_on:
                        - mysql
                networks:
                        - mysql
                        - web
                ports:
                        - ${MONICA_FALLBACK_PORT}:80
                environment:
                        - APP_ENV=production
                        - APP_URL=https://${MONICA_URL}
                        - DB_HOST=mysql
                        - DB_DATABASE=${MONICA_DB_DATABASE}
                        - DB_USERNAME=${MONICA_DB_USERNAME}
                        - DB_PASSWORD=${MONICA_DB_PASSWORD}
                        - DEFAULT_FILESYSTEM=s3
                        - AWS_KEY=${AWS_ACCESS_KEY_ID}
                        - AWS_SECRET=${AWS_SECRET_ACCESS_KEY}
                        - AWS_REGION=us-east-1
                        - AWS_BUCKET=${AWS_BUCKET}
                        - S3_PATH_STYLE=true
                        - MAIL_MAILER=smtp
                        - MAIL_HOST=email-smtp.us-east-1.amazonaws.com
                        - MAIL_PORT=587
                        - MAIL_USERNAME=${AWS_SES_SMTP_USERNAME}
                        - MAIL_PASSWORD=${AWS_SES_SMTP_PASSWORD}
                        - MAIL_ENCRYPTION=tls
                        - MAIL_FROM_ADDRESS=${AWS_SES_EMAIL_ADDRESS}
                        - MAIL_FROM_NAME="Monica"
                volumes:
                        - monica:/var/www/html/storage
                labels:
                        - traefik.enable=true
                        - traefik.docker.network=web
                        - traefik.http.routers.monica-insecure.rule=Host(`${MONICA_URL}`)
                        - traefik.http.routers.monica-insecure.entrypoints=web
                        - traefik.http.routers.monica.rule=Host(`${MONICA_URL}`)
                        - traefik.http.routers.monica.entrypoints=websecure
                        - traefik.http.routers.monica.tls=true
                        - traefik.http.routers.monica.tls.certresolver=letsencrypt
        traefik:
                container_name: traefik
                image: traefik:v2.6
                restart: unless-stopped
                ports:
                        - 80:80
                        - 443:443
                        - 8080:8080
                networks:
                        - web
                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock:ro
                        - ./traefik.yml:/etc/traefik/traefik.yml:ro
                        - ./acme.json:/etc/traefik/acme.json
                        - ./log/traefik/:/log/
                depends_on:
                        - monica
                labels:      
                        - "traefik.enable=true"
                        - "traefik.http.routers.traefik.entrypoints=web"
                        - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_URL}`)"
                        - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
                        - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
                        - "traefik.http.routers.traefik-secure.entrypoints=websecure"
                        - "traefik.http.routers.traefik-secure.rule=Host(`${TRAEFIK_URL}`)"
                        - "traefik.http.routers.traefik-secure.tls=true"
                        - "traefik.http.routers.traefik-secure.tls.certresolver=letsencrypt"
                        - "traefik.http.routers.traefik-secure.service=api@internal"
                        - "traefik.http.middlewares.traefik-auth.basicauth.removeHeader=true"
                        - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_BASIC_AUTH}"
                        - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
