version: '3.8'

networks:
        mysql:
        web:

volumes:
        monica:
                name: monica
        mysql:
                name: mysql

services:
        mysql:
                container_name: mysql
                image: mysql:5.7
                restart: always
                networks:
                        - mysql
                environment:
                        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
                volumes:
                        - mysql:/var/lib/mysql
                labels:
                        - traefik.enable=false
        monica:
                container_name: monica
                build: ./monica-app
                restart: always
                depends_on:
                        - mysql
                networks:
                        - mysql
                        - web
                environment:
                        - APP_ENV=production
                        - APP_URL=https://${MONICA_URL}
                        - DB_HOST=mysql
                        - DB_DATABASE=${MONICA_DB_DATABASE}
                        - DB_USERNAME=${MONICA_DB_USERNAME}
                        - DB_PASSWORD=${MONICA_DB_PASSWORD}
                        - DEFAULT_FILESYSTEM=s3
                        - AWS_KEY=${AWS_ACCESS_KEY_ID}
                        - AWS_SECRET=${AWS_SECRET_ACCESS_KEY}
                        - AWS_REGION=us-east-1
                        - AWS_BUCKET=${AWS_BUCKET}
                        - S3_PATH_STYLE=true
                        - MAIL_MAILER=smtp
                        - MAIL_HOST=email-smtp.us-east-1.amazonaws.com
                        - MAIL_PORT=587
                        - MAIL_USERNAME=${AWS_SES_SMTP_USERNAME}
                        - MAIL_PASSWORD=${AWS_SES_SMTP_PASSWORD}
                        - MAIL_ENCRYPTION=tls
                        - MAIL_FROM_ADDRESS=${AWS_SES_EMAIL_ADDRESS}
                        - MAIL_FROM_NAME="Monica"
                volumes:
                        - monica:/var/www/html/storage
                labels:
                        - traefik.enable=true
                        - traefik.http.routers.monica.rule=Host(`${MONICA_URL}`)
                        - traefik.http.routers.monica.entrypoints=websecure
                        - traefik.http.routers.monica.tls=true
                        - traefik.http.routers.monica.tls.certresolver=myresolver
        monica_fallback:
                container_name: monica_fallback
                image: monica:apache
                restart: always
                depends_on:
                        - mysql
                networks:
                        - mysql
                        - web
                ports:
                        - ${MONICA_FALLBACK_PORT}:80
                environment:
                        - APP_URL=http://${MONICA_URL}
                        - DB_HOST=mysql
                        - DB_DATABASE=${MONICA_DB_DATABASE}
                        - DB_USERNAME=${MONICA_DB_USERNAME}
                        - DB_PASSWORD=${MONICA_DB_PASSWORD}
                        - DEFAULT_FILESYSTEM=s3
                        - AWS_KEY=${AWS_ACCESS_KEY_ID}
                        - AWS_SECRET=${AWS_SECRET_ACCESS_KEY}
                        - AWS_REGION=us-east-1
                        - AWS_BUCKET=${AWS_BUCKET}
                        - S3_PATH_STYLE=true
                volumes:
                        - monica:/var/www/html/storage
                labels:
                        - traefik.enable=true
                        - traefik.http.routers.monica_fallback.rule=Host(`${MONICA_URL}`)
                        - traefik.http.routers.monica_fallback.entrypoints=web
        traefik:
                container_name: traefik
                image: traefik:v2.5
                restart: always
                ports:
                        - 80:80
                        - 443:443
                        - 8080:8080
                networks:
                        - web
                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock
                        - ./traefik.yml:/etc/traefik/traefik.yml
                        - ./acme.json:/etc/traefik/acme.json
                depends_on:
                        - monica
                        - monica_fallback
                labels:
                        - traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_URL}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
                        - traefik.http.routers.dashboard.service=api@internal
                        - traefik.http.routers.dashboard.middlewares=auth
                        - traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_BASIC_AUTH}
