entryPoints:
  web:
    address: ':80'

  websecure:
    address: ':443'

providers:
  docker: {}

certificatesResolvers:
  myresolver:
    acme:
      email: pedro@arantespp.com
      storage: /etc/traefik/acme.json
      tlsChallenge: true

api:
  insecure: false
  dashboard: true
