entryPoints:
  web:
    address: ':80'

  websecure:
    address: ':443'

log:
  level: DEBUG
  filePath: /log/traefik.log

accessLog:
  filePath: /log/access-log.txt

providers:
  docker: {}

certificatesResolvers:
  myresolver:
    acme:
      email: pedro@arantespp.com
      storage: /etc/traefik/acme.json
      tlsChallenge: true

api:
  insecure: false
  dashboard: true
