entryPoints:
  web:
    address: ':80'
    # Reference: https://doc.traefik.io/traefik/routing/entrypoints/#redirection
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ':443'

log:
  level: DEBUG
  filePath: /log/traefik.log

accessLog:
  filePath: /log/access-log.txt

providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    exposedByDefault: false
    # The same name on docker-compose networks.
    network: web

  file:
    filename: /etc/traefik/traefik.yml
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: pedro@arantespp.com
      storage: /etc/traefik/acme.json
      keyType: 'RSA4096'
      tlsChallenge: true

api:
  insecure: false
  dashboard: true
