version: '3.8'

networks:
        mysql:
                external: true

services:
        monica:
                build: ../monica-app
                networks:
                        - mysql
                ports:
                        - ${MONICA_PORT}:80
                environment:
                        - APP_ENV=production
                        - APP_URL=https://${MONICA_URL}
                        - DB_HOST=mysql
                        - DB_DATABASE=${MONICA_DB_DATABASE}
                        - DB_USERNAME=${MONICA_DB_USERNAME}
                        - DB_PASSWORD=${MONICA_DB_PASSWORD}
                        - MAIL_MAILER=smtp
                        - MAIL_HOST=email-smtp.us-east-1.amazonaws.com
                        - MAIL_PORT=587
                        - MAIL_USERNAME=${AWS_SES_SMTP_USERNAME}
                        - MAIL_PASSWORD=${AWS_SES_SMTP_PASSWORD}
                        - MAIL_ENCRYPTION=tls
                        - MAIL_FROM_ADDRESS=${AWS_SES_EMAIL_ADDRESS}
                        - MAIL_FROM_NAME="Monica"
